domain: lucteyssier.com
url: "https://lucteyssier.com"
baseurl: ""

source: _site
destination: docs
disable_disk_cache: true

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false

include:
  - CNAME
keep_files:
  - CNAME


# SEO
title: "Luc Teyssier"
description: Writer
